CREATE TABLE TRAINER (
	id UUID DEFAULT RANDOM_UUID() PRIMARY KEY
);
CREATE TABLE USERS (
	id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
	first_name VARCHAR(70) NOT NULL,
	last_name VARCHAR(70) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE POKEMON (
	id UUID PRIMARY KEY
);